Repository Dron010/filmoteka, pull requests merged in 2021-11, with the labels that each got.

#49 fix modal-style
  package-lock.json
  src/js/components/modal.js
  src/js/layout/fetch-by-Id.js
  src/js/refs/refs.js
  src/partial/layouts/backdrop.html
  src/partial/templates/modal-film.hbs
  src/sass/components/_modal-btn.scss
  src/sass/components/_modal.scss
Labels: wontfix

#41 Origin switch them
  src/images/icon/sprite.svg
  src/index.js
  src/js/layout/switchTheme.js
  src/js/refs/refs.js
  src/partial/layouts/header.html
  src/partial/layouts/thems.html
  src/sass/layout/_theme-switch.scss
  src/sass/main.scss
  src/sass/utils/_vars.scss
Labels: question

#43 Feature/scroll up
  src/images/icon/sprite.svg
  src/index.html
  src/index.js
  src/js/components/scroll-to-top.js
  src/js/refs/refs.js
  src/partial/components/scroll-top.html
  src/sass/components/_scroll-top.scss
  src/sass/main.scss
Labels: question

#70 Featch modal slider
  src/js/api/api-service.js
  src/js/components/arrow-modal.js
  src/js/layout/switchTheme.js
  src/partial/templates/modal-film.hbs
  src/sass/components/_arrow-modal.scss
  src/sass/main.scss
Labels: good first issue

#65 Bagfix/contacts modal
  src/contacts.json
  src/images/icon/github-logo.png
  src/images/icon/sprite.svg
  src/index.js
  src/js/components/contacts.js
  src/js/refs/refs.js
  src/partial/layouts/footer.html
  src/partial/templates/contacts-list.hbs
  src/partial/templates/modal-film.hbs
  src/sass/components/_contacts.scss
  src/sass/layout/_footer.scss
  src/sass/main.scss
Labels: duplicate

#68 Feature/something else
  src/images/content/background/popcorn.webp
  src/index.js
  src/js/components/background.js
  src/js/layout/switchTheme.js
  src/js/refs/refs.js
  src/partial/layouts/main.html
  src/sass/base/_global-style.scss
  src/sass/components/_scroll-top.scss
  src/sass/layout/_list-cards-movies.scss
  src/sass/layout/_theme-switch.scss
Labels: enhancement

#78 Исправил spiner и размер картинок в модалке и мейне
  src/js/api/api-service.js
  src/sass/layout/_list-cards-movies.scss
Labels: good first issue

#86 Bag fix/modal structure & destructuring
  src/js/components/modal.js
  src/sass/components/_modal.scss
Labels: good first issue

#82 add colors for dark-theme and some fix html
  src/partial/templates/contacts-list.hbs
  src/sass/components/_contacts.scss
  src/sass/layout/_theme-switch.scss
  src/sass/utils/_vars.scss
Labels: good first issue

#84 Feature/scroll up
  src/js/components/scroll-to-top.js
  src/partial/components/scroll-top.html
  src/sass/components/_scroll-top.scss
Labels: good first issue

#87 Fix/notify add backgrounds
  src/js/components/notifications.js
Labels: good first issue

#109 Feature/modal arrows mod
  src/index.js
  src/js/components/arrows-on-modal.js
  src/js/components/contacts.js
  src/js/components/modal.js
  src/js/layout/fetch-by-Id.js
  src/partial/layouts/backdrop.html
  src/partial/templates/modal-film.hbs
  src/sass/components/_modal-arrows.scss
  src/sass/components/_pagination.scss
  src/sass/layout/_list-cards-movies.scss
  src/sass/main.scss
Labels: wontfix

#81 Origin/feature/switch films on click
  src/index.js
  src/js/components/arrows-on-modal.js
  src/js/layout/fetch-by-Id.js
  src/partial/layouts/backdrop.html
  src/partial/templates/modal-film.hbs
  src/sass/components/_modal-arrows.scss
  src/sass/main.scss
Labels: duplicate
